Add alias on UseNetwork()
mariotoffia/FluentDocker pull request #172
Opened 2021-01-27 00:15 UTC by fbraun4358

# Changes
I ran into the issue that I wanted to attach containers to pre-created networks via `UseNetwork(params string[] network)` and `UseNetwork(params INetworkService[] network)` but there is no way to pass an alias.

`DockerHost.NetworkAttach` already has the ability to take in the alias to use so I added the ability to pass an alias via `UseNetwork()`. The alias will be used for every network passed in the params array. Because the first network is added via the container create parameters I added `--network-alias` to `ContainerCreateParams`.

To keep the API as backward compatible as possible I added `alias` as an optional parameter where it was added. The only change to the external API is in the class `ContainerBuilderConfig` which has the types of `Networks` and `NetworkNames` changed.

# Tests
I was trying to figure out where I should be adding tests to make sure this is working but I am not totally following the testing structure. Some pointers in the right direction would be really helpful.

2021-01-27 20:04 UTC, mariotoffia requested changes
Thanks for the PR! :) - I think we need to discuss a little bit about this implementation - see comments

Cheers,
 Mario :)

2021-01-27 20:04 UTC, mariotoffia commented on Ductus.FluentDocker/Builders/ContainerBuilder.cs
> +    /// <param name="alias">The alias to use when attaching this container to the given networks.</param>
Please move the alias parameter before network since to match order

2021-01-27 20:04 UTC, mariotoffia commented on Ductus.FluentDocker/Builders/ContainerBuilder.cs
> +    public ContainerBuilder UseNetwork(string alias, params INetworkService[] network)
I need to revisit your description of the PR but since alias is optional everywhere why do we need to specify this in the `UseNetwork` ?

2021-01-27 20:04 UTC, mariotoffia commented on Ductus.FluentDocker/Builders/ContainerBuilder.cs
> +        network.Select(n => new NetworkAttachConfiguration { Alias = alias, Network = n}));
I'm not familiar with alias, how does it work? Isn't alias for one single network and not for all networks?

2021-01-27 20:04 UTC, mariotoffia commented on Ductus.FluentDocker/Builders/ContainerBuilder.cs
> +    /// <summary>
Same comments as method above.

2021-01-27 22:07 UTC, fbraun4358 commented
# Aliases
A container's `alias` is the name of the container in the network when doing network calls. This way you don't need to know the IP of the specific container within the network. Say you have a container running a web service. The service is listening on `0.0.0.0:8080`. By default the docker network does not forward the `8080` port to the host machine. If you want to connect to the service you either need to forward the port, like `-p 8080:80`, or you can add another container to the network. When you add that container to the network you can access the web service via `http://<ws container id>:8080`, if you know the IP. By giving the web service container an alias you can then connect to the web service while inside the network via `http://<container alias>:8080`.

Since the container IP can change unless you force an IP, the alias allows you to connect to services running in a container via the alias without needing to know the specific IP.

# API Changes
As to the change in the API on `ContainerBuilderConfig`, This was the only way I could figure out how to get the alias from `UseNetworks()` to `DockerHost.NetworkAttach`. The way it is implemented now it is possible to give the container a different alias for each network.

Given the below, the container would be connected to networks 1 and 2 with the alias `alias` and it would be connected to the third network as `alias2`.
```C#
builder.UseNetwork("alias", network1, network2)
    .UseNetwork("alias2", network3);
```

The other option I thought of was adding a method like `ContainerBuilder.UseAlias(string alias)` and then just use that single alias for all networks. This second option is better to keep API compatibility but it does remove some flexibility of allowing an alias on a per network basis. I can rework the implementation to do this, then there would be no API change, just another property on `ContainerBuilderConfig`.

2021-01-28 12:36 UTC, mariotoffia commented
> # API Changes
> As to the change in the API on `ContainerBuilderConfig`, This was the only way I could figure out how to get the alias from `UseNetworks()` to `DockerHost.NetworkAttach`. The way it is implemented now it is possible to give the container a different alias for each network.
> 
> The other option I thought of was adding a method like `ContainerBuilder.UseAlias(string alias)` and then just use that single alias for all networks. This second option is better to keep API compatibility but it does remove some flexibility of allowing an alias on a per network basis. I can rework the implementation to do this, then there would be no API change, just another property on `ContainerBuilderConfig`.

Thanks! Really! for your explanation :) 

hmmm... a bit more ugly way of solving it and **still** have API compatibility is to introduce two new set of builder methods - e.g.

`UseNetworkWithAlias(...)` or `UseAliasedNetwork(...)` and keep the `UseNetwork(...)` methods as it where before your PR. Then in 2.0.0 we merge those into the same method name `UseNetwork(...)` as you have done. 

We would not break the API since that's mandatory in same major version but have two options when we configure the network. However, choosing `UseNetworkWithAlias` would give those with autocompletion good guidance.

Cheers,
 Mario :)

2021-02-08 09:40 UTC, mariotoffia commented
Hey @fbraun4358  what do you think about my proposal above?

2021-02-08 21:53 UTC, fbraun4358 commented
@mariotoffia

Hey, sorry for being MIA. I have been taking a look at it on and off but am really limited now with work so not really anything worth pushing.

I think the biggest thing I am running into is that this turns into having the same code duplicated 4 times essentially. Once for each `UseNetwork(INetworkService)`, `UseNetwork(string)`, `UseNetworkWithAlias(INetworkService)`, `UseNetworkWithAlias(string)`. And then ordering the precedence of all of these. I assume the `INetworkService` before `string` but then do we use the `WithAlias` ones before or after the standard ones.

Maybe having it 4 times tight now is fine and then clean up in version 3 or maybe just implement it only for version 3?

2021-02-09 21:05 UTC, mariotoffia commented
@fbraun4358 

> I think the biggest thing I am running into is that this turns into having the same code duplicated 4 times essentially. Once for each `UseNetwork(INetworkService)`, `UseNetwork(string)`, `UseNetworkWithAlias(INetworkService)`, `UseNetworkWithAlias(string)`. And then ordering the precedence of all of these. I assume the `INetworkService` before `string` but then do we use the `WithAlias` ones before or after the standard ones.

Agreed a bit messy! But in regards to priority it is still the same "unintuitive" way of "first network registered wins" independant on how and what method was executed. In v3 there's a plan on a `NetworkBuilder` so it will be much mor explicit, e.g `DefaultNetwork` etc.

> Maybe having it 4 times tight now is fine and then clean up in version 3 or maybe just implement it only for version 3?

I think that's doable.

Cheers,
 Mario

2021-02-19 01:44 UTC, fbraun4358 commented
I restarted and added a new PR: #173

2021-02-19 01:44 UTC, closed without merging